Serve NativeX stories
parameter1/randall-reilly-websites pull request #217
Opened 2021-03-31 16:18 UTC by solocommand

Utilizes new middleware from parameter1/base-cms#60 to retrieve a story and render it on the site.

- [x] Render NativeX story following content layout
- [ ] Port GTM and add events
  - [ ] Hook social share via EventBus
  - [ ] Create observer to fire when reaching the bottom of the page
- [ ] Resolve backend 400 when rendering story page

![screencapture-localhost-9804-sponsored-driving-tests-insights-into-trucking-and-transportation-companies-show-hiring-difficulties-and-issues-keeping-drivers-employed-604a5ac81b33df0001a464b9-2021-03-31-11_13_35](https://user-images.githubusercontent.com/1778222/113176603-49ca6680-9212-11eb-80ca-c2866ff7e87b.png)

2021-03-31 16:18 UTC, solocommand commented
![](https://github.trello.services/images/mini-trello-icon.png) [Embed Native-X stories within the site](https://trello.com/c/rHbOMWJt/48-embed-native-x-stories-within-the-site)

2021-03-31 16:50 UTC, zarathustra323 requested changes

2021-03-31 16:50 UTC, zarathustra323 commented on packages/global/routes/native-x.js
> +const WithNativeXStory = require('@parameter1/base-cms-marko-web-native-x/middleware/with-story');
`camelCase` this please

2021-03-31 16:50 UTC, zarathustra323 commented on packages/global/templates/content/components/presented-by.marko
> +$ const imgDefaults = { auto: 'format,compress', h: 50, q: 70 };
Check quote style throughout

2021-03-31 16:50 UTC, zarathustra323 commented on packages/global/templates/content/components/presented-by.marko
> +
Delete L9 and L10....

Then add after L12
```marko
$ const src = buildImgixUrl(imgSrc, imgDefaults);
$ const srcset = [`${src}&dpr=2`];
```

Then L19 and L20 become `src=src` and `srcset=srcset`

2021-04-05 16:41 UTC, zarathustra323 requested changes

2021-04-05 16:41 UTC, zarathustra323 commented on packages/global/templates/content/components/presented-by.marko
> +$ const style = { "max-width": "100%", height: 50 };
50 should be 50px

2021-04-05 16:41 UTC, zarathustra323 commented on packages/global/templates/content/components/presented-by.marko
> +  $ const src = imgSrc && buildImgixUrl(imgSrc, imgDefaults);
The imgSrc check isn't needed here

2021-04-05 16:41 UTC, zarathustra323 commented on packages/global/templates/content/native-x-story.marko
> +        <span class="d-none"></span>
Is there a reason for this empty element?

2021-04-05 17:16 UTC, solocommand commented on packages/global/templates/content/native-x-story.marko
> +        <span class="d-none"></span>
Was using it to push the content header down; I've reworked to a new modifier for this purpose.

2021-04-06 15:05 UTC, zarathustra323 approved these changes

2021-04-06 15:05 UTC, merged