Update fields in Equipment Experts API
parameter1/randall-reilly-websites pull request #243
Opened 2021-06-09 20:51 UTC by Shinsina

The CSV is only there because it constantly ends back up in my staging area even if I discard local changes, delete the file, etc.

2021-06-09 21:03 UTC, solocommand requested changes

2021-06-09 21:03 UTC, solocommand commented on packages/equipment-experts/index.js
> +      path: 'https://github.com/Shinsina/randall-reilly-websites',
The CSV is fine, it's fixing whitespace that should have been fixed previously. However, this isn't the correct value for the `meta.path` parameter. Check the old API (in the trello card) to see what was present for this field

2021-06-09 21:04 UTC, solocommand commented
![](https://github.trello.services/images/mini-trello-icon.png) [Modify Equipment Experts API](https://trello.com/c/RrNgpEmG/63-modify-equipment-experts-api)

2021-06-09 21:07 UTC, solocommand commented on packages/equipment-experts/index.js
> +      path: 'https://github.com/Shinsina/randall-reilly-websites',
Most likely you're going to want to use the request object to the the current URL. IIRC this is what they used to key off of for pagination in their old system.

2021-06-09 21:47 UTC, Shinsina commented on packages/equipment-experts/index.js
> +      path: 'https://github.com/Shinsina/randall-reilly-websites',
My bad on the URL I had to reset my local instance of the repo and that just so happened to be what was on my clipboard.

2021-06-09 22:02 UTC, Shinsina commented
I figured out what your comment meant give me a bit

2021-06-10 14:33 UTC, solocommand approved these changes

2021-06-10 14:34 UTC, merged