Addition of author bio for contributors on article
parameter1/randall-reilly-websites pull request #245
Opened 2021-06-17 14:51 UTC by Shinsina

<img width="1920" alt="Screen Shot 2021-06-17 at 9 38 42 AM" src="https://user-images.githubusercontent.com/46794001/122420785-8aa06480-cf51-11eb-9c4b-81ba18eba991.png">

2021-06-17 14:51 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Display author bio at end of article for contributors](https://trello.com/c/XNF6cGAB/64-display-author-bio-at-end-of-article-for-contributors)

2021-06-17 16:54 UTC, Shinsina commented
<img width="1920" alt="Screen Shot 2021-06-17 at 11 53 55 AM" src="https://user-images.githubusercontent.com/46794001/122441049-c7288c00-cf62-11eb-9c49-b23770fd8e88.png">

2021-06-25 16:25 UTC, solocommand requested changes

2021-06-25 16:25 UTC, solocommand commented on packages/global/components/layouts/content/default.marko
> +$ let contentContactLength = null
Don't use let. If you need access to these variables across multiple sections, define the values at a higher level.

2021-06-25 16:25 UTC, solocommand commented on packages/global/components/layouts/content/default.marko
> +
Review indentation

2021-06-28 15:24 UTC, zarathustra323 requested changes

2021-06-28 15:24 UTC, zarathustra323 commented on packages/global/components/nodes/author-published.marko
> +$ const showPublished = input.showPublished || true
A `false` value will never work here... since `input.showPublished` of false will fallback to true due to the inline or (`||`) statement. Instead, import the `defaultValue` utility from `@parameter1/base-cms-marko-web-core` and use that instead

2021-06-28 15:24 UTC, zarathustra323 commented on packages/global/components/layouts/content/default.marko
> +          <if(authors.length === 1 && contentContactLength < 2)>
Can you explain why the total contact length needs to be less than two here?

2021-06-28 15:24 UTC, zarathustra323 commented on packages/global/components/layouts/content/wrapper.marko
> +      $ const authors = getAsArray(content, "authors.edges");
I would map the author nodes here, not the edges so the author nodes are easier to work with, i.e. `getAsArray(content, "authors.edges").map((edge) => edge.node);`

2021-06-28 15:24 UTC, zarathustra323 commented on packages/global/components/layouts/content/default.marko
>            <global-author-published-node author=authors[0].node content=content />
Change this to `authors[0]` now... since we're going to be mapping the author nodes instead of passing the author edges

2021-06-28 15:24 UTC, zarathustra323 commented on packages/global/components/layouts/content/default.marko
> +              <if (!author.node.name.includes('Staff'))>
Change this to `author.name` now since the nodes will be mapped instead of passing the edges. You should also make sure that the name actually exists, and isn't null (otherwise this will error, because the `includes` function will not exist on a non-string (e.g. on a null or undefined value)... so `<if(author.name && author.name.includes('Staff')>`

2021-06-28 15:24 UTC, zarathustra323 commented on packages/global/components/layouts/content/default.marko
> +                <global-author-published-node author=author.node content=content showPublished=false />
Change to `author` since the nodes are being mapped directly

2021-06-28 15:24 UTC, zarathustra323 commented on packages/global/components/layouts/content/default.marko
> +              <if (author.node.body !== '')>
Change all of these references to `author.body`... also, bodies can also be null, not just an empty string. Instead just check for a truthy value... e.g. `<if(author.body)>`

2021-06-28 15:55 UTC, Shinsina commented
<img width="1920" alt="Screen Shot 2021-06-28 at 10 42 53 AM" src="https://user-images.githubusercontent.com/46794001/123666931-463d8000-d7ff-11eb-8ab1-17ded9b0d6d6.png">

This should also account for articles with multiple contributors.

2021-06-28 16:31 UTC, zarathustra323 requested changes

2021-06-28 16:31 UTC, zarathustra323 commented on packages/global/components/layouts/content/default.marko
> +              <if(author.body)>
Move L141-143 right after L139

2021-06-28 16:31 UTC, zarathustra323 approved these changes

2021-06-28 16:36 UTC, merged