Add sponsor logos sda tps
parameter1/randall-reilly-websites pull request #281
Opened 2021-08-31 18:45 UTC by Shinsina

<img width="1920" alt="Screen Shot 2021-08-31 at 1 41 25 PM" src="https://user-images.githubusercontent.com/46794001/131558676-f6e23574-ff44-4326-b2d4-9f77fb8ce1d4.png">

2021-08-31 18:45 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [TPS: Add Sponsor Logos to Successful Dealer Award page](https://trello.com/c/ZcGtP7RM/82-tps-add-sponsor-logos-to-successful-dealer-award-page)

2021-09-13 15:05 UTC, brandonbk requested changes

2021-09-13 15:05 UTC, brandonbk commented on packages/global/components/blocks/successful-dealer-sponsors.marko
> +      <marko-web-img
Update this to use buildImgixUrl

2021-09-13 17:07 UTC, brandonbk approved these changes

2021-09-13 17:08 UTC, merged