Use new theme ssr ad injection comp for content body & transcript
parameter1/randall-reilly-websites pull request #498
Opened 2022-11-22 15:42 UTC by B77Mills

### Requires: https://github.com/parameter1/base-cms/pull/494 & a base-cms release and dep upgrade done on this repo.

Utilize the newly added monorail theme component for ssr ad injection into the content & transcript fields on content.  

This call to render body and transcript field on RR sites.
```marko.js
$ const leaderboardAdName = (GAM.btfLeaderboard) ? "inline-leaderboard-mobile" : "inline-content-mobile";
$ const leaderboardModifiers = (GAM.btfLeaderboard) ? ["margin-auto-x",  "inline-content", "inline-leaderboard-mobile"] : ["margin-auto-x",  "inline-content", "inline-mobile"];
<theme-body-with-injection
  content=content
  aliases=aliases
  block-name=blockName
  preventHTMLInjection=!shouldInjectAds
  ad-injection-config = [
    {
      name: 'inline-content-desktop',
      modifiers: ["margin-auto-x",  "inline-content", "inline-content-desktop"],
      counts: [1000, 2750, 4500, 6250, 8000, 9750, 11500, 13250, 15000, 16750, 18500],
    },
    {
      name: leaderboardAdName,
      modifiers: leaderboardModifiers,
      counts: [250],
    },
    {
      name: 'inline-content-mobile',
      modifiers: ["margin-auto-x",  "inline-content", "inline-content-mobile"],
      counts: [900, 1650, 2950, 4250, 5550, 6850, 8150, 9450, 10750, 12050, 13350, 14650, 15950, 17250],
    }
  ]
/>
<if(content.transcript)>
  <div id=`transcript-${id}` class="page-contents__content-transcript">
    <marko-web-element block-name="page-contents" name="content-transcript-title">
      <marko-web-icon name="file" modifiers=["lg"] /> Transcript
    </marko-web-element>
    <theme-body-with-injection
      content={ body: content.transcript }
      aliases=aliases
      block-name=blockName
      preventHTMLInjection=!shouldInjectAds
    />
  </div>
</if>
```

2022-11-23 14:39 UTC, B77Mills commented
![](https://github.trello.services/images/mini-trello-icon.png) [CLS: Body copy shifting when ads load on mobile](https://trello.com/c/aQnuynEI/193-cls-body-copy-shifting-when-ads-load-on-mobile)

2022-11-30 13:28 UTC, brandonbk requested changes

2022-11-30 13:28 UTC, brandonbk commented on packages/global/components/layouts/content/default.marko
> +$ const { global: $global } = out;
This doesn't appear to be used anywhere; can it be removed?

2022-11-30 19:30 UTC, brandonbk approved these changes

2022-12-01 14:21 UTC, merged