Rigdig thr
parameter1/randall-reilly-websites pull request #591
Opened 2023-08-29 19:17 UTC by B77Mills

2023-08-30 17:57 UTC, B77Mills commented
![](https://github.trello.services/images/mini-trello-icon.png) [Initial Setup of RigDig site.](https://trello.com/c/o5LsaHmQ/272-initial-setup-of-rigdig-site)

2023-09-05 14:30 UTC, solocommand requested changes
A few changes -- consolidate CSS and configs. Did Rob/group supply a new THR logo, or is the RigDig one a placeholder?

2023-09-05 14:30 UTC, solocommand commented on sites/truckhistoryreport.com/config/site.js
> +    cookieDomain: process.env.NODE_ENV === 'production' ? 'truckhistoryreport.com' : '',
`truckhistory.overdriveonline.com` or `overdriveonline.com`

2023-09-05 14:30 UTC, solocommand commented on sites/truckhistoryreport.com/server/styles/components/_rigdig.scss
Move this to the rigdig package, now that it's being used in two places.

2023-09-05 14:30 UTC, solocommand commented on sites/truckhistoryreport.com/config/site.js
Move all of these local configs to a new package (`packages/overdrive`) and import them in both OVD and THR. That way you only have to make changes in one pace, and they will stay in sync. Since THR is a subdomain, having the cookie domain set to `overdriveonline.com` will work fine.

2023-09-07 15:25 UTC, solocommand approved these changes

2023-09-07 15:32 UTC, merged