Create and utilize redirect handler for HWT
parameter1/randall-reilly-websites pull request #775
Opened 2024-11-07 22:46 UTC by Shinsina

2024-11-07 22:46 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Remapping Hard Working Trucks Content to CCJ, Equipment World, Clean Trucking and TPS](https://trello.com/c/MOGz4Z4z/420-remapping-hard-working-trucks-content-to-ccj-equipment-world-clean-trucking-and-tps)

2024-11-08 15:20 UTC, solocommand requested changes

2024-11-08 15:20 UTC, solocommand commented on packages/global/middleware/hwt-redirect-handler.js
> +    return res.redirect(301, 'https://www.ccjdigital.com');
This redirect should retain the existing URI on the new domain -- so if a user attempts to access non-primary content on HWT, they are sent to the content URL on HWT. This will incur an extra redirect (or two), but that's okay in this case, since it was non-primary anyway (and wouldn't have an SEO impact since the SEO value belongs to the canonical site)

2024-11-08 15:46 UTC, solocommand approved these changes

2024-11-08 15:47 UTC, merged